# Default Profile
[profile.default]
evm_version = "shanghai"
ffi = false
fs_permissions = [{ access = "read-write", path = "./"}]
fuzz_runs = 256
optimizer = true
optimizer_runs = 1_000_000
remappings = [
  "@chainlink=lib/chainlink/contracts/src/v0.8/",
  "@solidstate/contracts/=lib/solidstate-solidity/contracts/",
  "forge-safe/=lib/forge-safe/src/",
  "forge-std/=lib/forge-std/src/",
]
solc_version = '0.8.19'
src = "contracts"
verbosity = 1

# CI Profile
[profile.CI]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
arb_fork_tenderly = "${PERP_MINT_ARB_URL}"
arbitrum-one = "${ARBITRUM_RPC_URL}"
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
blast = "${BLAST_RPC_URL}"
blast-sepolia = "${BLAST_SEPOLIA_RPC_URL}"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}" }
arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
base-sepolia = { key = "${BASESCAN_API_KEY}" }
blast = { key = "${BLASTSCAN_API_KEY}" }
blast-sepolia = { chain = "168587773", key = "${BLASTSCAN_API_KEY}", url = "${BLASTSCAN_VERIFIER_URL}" }
